import { describe, expect, it } from 'vitest';
import { claudeConversationId } from '../content/providers/claude'; import { qwenConversationId } from '../content/providers/qwen'; import { grokConversationId } from '../content/providers/grok';
import { geminiConversationId } from '../content/providers/gemini'; import { metaAiConversationId } from '../content/providers/metaai'; import { miniMaxConversationId } from '../content/providers/minimax'; import { aristotleConversationId } from '../content/providers/aristotle';
describe('provider conversation ID extraction', () => {
  it('preserves earlier providers', () => { expect(claudeConversationId('https://claude.ai/chat/c1')).toBe('c1'); expect(qwenConversationId('https://chat.qwen.ai/chat/q1')).toBe('q1'); expect(grokConversationId('https://grok.com/chat/g1')).toBe('g1'); });
  it('extracts Gemini app, user app, and chat routes', () => { expect(geminiConversationId('https://gemini.google.com/app/g1')).toBe('g1'); expect(geminiConversationId('https://gemini.google.com/u/0/app/g2')).toBe('g2'); expect(geminiConversationId('https://gemini.google.com/chat/g3')).toBe('g3'); expect(geminiConversationId('https://gemini.google.com/')).toBeNull(); });
  it('extracts Meta AI routes', () => { expect(metaAiConversationId('https://www.meta.ai/chat/m1')).toBe('m1'); expect(metaAiConversationId('https://meta.ai/messages/m2')).toBe('m2'); expect(metaAiConversationId('https://meta.ai/')).toBeNull(); });
  it('extracts MiniMax chat, agent, and task routes', () => { expect(miniMaxConversationId('https://agent.minimax.io/chat/x1')).toBe('x1'); expect(miniMaxConversationId('https://agent.minimax.io/agent/x2')).toBe('x2'); expect(miniMaxConversationId('https://agent.minimax.io/task/x3')).toBe('x3'); expect(miniMaxConversationId('https://minimax.io/')).toBeNull(); });
  it('extracts every Aristotle context route', () => { expect(aristotleConversationId('https://aristotle.science/chat/a1')).toBe('a1'); expect(aristotleConversationId('https://aristotle.science/conversation/a2')).toBe('a2'); expect(aristotleConversationId('https://aristotle.science/thread/a3')).toBe('a3'); expect(aristotleConversationId('https://aristotle.science/research/a4')).toBe('a4'); expect(aristotleConversationId('https://aristotle.science/')).toBeNull(); });
});
