import { beforeEach, describe, expect, it, vi } from 'vitest'; import { migrationLockAvailable, validQueueMigration } from '../lib/migration'; import { mergeQueuesForMigration, migrateStorageSnapshot } from '../lib/storage'; import type { QueueItem } from '../lib/types';
beforeEach(() => vi.stubGlobal('crypto',{ randomUUID:vi.fn(()=>'generated-id') })); const item=(id:string,text=id):QueueItem=>({id,text,source:'manual',status:'queued',createdAt:1,updatedAt:1});
const ids=['chatgpt','claude','qwen','mistral','huggingchat','grok','kimi','perplexity','zai','sakana','longcat','gemini','metaai','minimax','aristotle']; const maps=()=>Object.fromEntries(ids.map(id=>[id,{}]));
describe('storage migration',()=>{
  it('migrates schema v1 into ChatGPT scope',()=>{const r=migrateStorageSnapshot({schemaVersion:1,queuesByConversation:{'conversation:a':[item('1')]},pausedByConversation:{'conversation:a':true}});expect(r.state.schemaVersion).toBe(5);expect(r.state.queuesByProvider.chatgpt['conversation:a'][0].id).toBe('1');});
  it('migrates schema v4 without losing any Phase 3 data or enablement',()=>{const q=Object.fromEntries(ids.slice(0,11).map(id=>[id,{}]));q.longcat={c:[item('l')]};const p=Object.fromEntries(ids.slice(0,11).map(id=>[id,{}]));p.longcat={c:true};const r=migrateStorageSnapshot({schemaVersion:4,settings:{},providerEnablement:{claude:true,grok:true,longcat:true},queuesByProvider:q,pausedByProvider:p});expect(r.changed).toBe(true);expect(r.state.queuesByProvider.longcat.c[0].id).toBe('l');expect(r.state.pausedByProvider.longcat.c).toBe(true);expect(r.state.providerEnablement).toMatchObject({claude:true,grok:true,longcat:true,gemini:false,metaai:false,minimax:false,aristotle:false});});
  it('accepts valid selector overrides in schema v5',()=>{const q=maps(),p=maps();const r=migrateStorageSnapshot({schemaVersion:5,settings:{},providerEnablement:{gemini:true},queuesByProvider:q,pausedByProvider:p,selectorOverridesByProvider:{gemini:{composer:['.custom']}}});expect(r.changed).toBe(false);expect(r.state.selectorOverridesByProvider.gemini).toEqual({composer:['.custom']});});
  it('drops invalid selector overrides safely',()=>{const r=migrateStorageSnapshot({schemaVersion:4,settings:{},queuesByProvider:Object.fromEntries(ids.slice(0,11).map(id=>[id,{}])),pausedByProvider:Object.fromEntries(ids.slice(0,11).map(id=>[id,{}])),selectorOverridesByProvider:{gemini:{composer:['javascript:bad']}}});expect(r.state.selectorOverridesByProvider).toEqual({});});
  it('backs up future and malformed current schemas',()=>{expect(migrateStorageSnapshot({schemaVersion:99}).backup).toBeTruthy();expect(migrateStorageSnapshot({schemaVersion:5,queuesByProvider:{chatgpt:'bad'},pausedByProvider:{}}).backup).toBeTruthy();});
});
describe('temporary queue migration',()=>{
  it('merges without duplicates or mutating unrelated queues',()=>{const unrelated=[item('x')];expect(mergeQueuesForMigration([item('1')],[item('1'),item('2')]).map(x=>x.id)).toEqual(['1','2']);expect(unrelated.map(x=>x.id)).toEqual(['x']);});
  it('rejects wrong-provider and malformed queue migrations',()=>{expect(validQueueMigration('gemini','temp:metaai:tab:1','conversation:g','owner')).toBe(false);expect(validQueueMigration('gemini','temp:gemini:tab:1','conversation:g','owner')).toBe(true);expect(validQueueMigration('gemini','temp:gemini:tab:1','temp:gemini:tab:2','owner')).toBe(false);});
  it('prevents concurrent lock owners',()=>{const lock={owner:'one',acquiredAt:1000};expect(migrationLockAvailable(lock,'two',2000)).toBe(false);expect(migrationLockAvailable(lock,'one',2000)).toBe(true);expect(migrationLockAvailable(lock,'two',12000)).toBe(true);});
});
