import { useState } from 'react';
import { createSafeDiagnosticCopy } from '../../lib/diagnostics';
import type { ProviderDiagnostics, SchedulerState } from '../../lib/types';
function Row({ label, value }: { label: string; value: string }) { return <div className="flex gap-3 py-1"><dt className="w-32 shrink-0 text-zinc-500">{label}</dt><dd className="min-w-0 break-all font-mono">{value}</dd></div>; }
export function DiagnosticsPanel({ diagnostics, leader, scheduler }: { diagnostics: ProviderDiagnostics; leader: boolean; scheduler?: SchedulerState }) {
  const [copyState, setCopyState] = useState<'idle' | 'copied' | 'failed'>('idle'); const yes = (value: boolean) => value ? 'yes' : 'no';
  const copy = async () => { try { await navigator.clipboard.writeText(JSON.stringify(createSafeDiagnosticCopy(diagnostics, leader, scheduler), null, 2)); setCopyState('copied'); } catch { setCopyState('failed'); } };
  return <section className="card p-4"><div className="flex items-center justify-between gap-2"><h2 className="text-sm font-semibold">Debug diagnostics</h2><button className="btn" onClick={() => void copy()}>{copyState === 'copied' ? 'Copied' : copyState === 'failed' ? 'Copy failed' : 'Copy diagnostics'}</button></div><dl className="mt-3 text-[11px]"><Row label="Provider" value={diagnostics.providerName + ' (' + diagnostics.providerId + ')'} /><Row label="URL" value={diagnostics.url} /><Row label="Conversation" value={diagnostics.conversationId ?? diagnostics.temporaryConversationKey} /><Row label="Composer" value={yes(diagnostics.composerFound) + ' · ' + diagnostics.composerType} /><Row label="Send / stop" value={yes(diagnostics.sendButtonFound) + ' / ' + yes(diagnostics.stopButtonFound)} /><Row label="Response control" value={yes(diagnostics.regenerateButtonFound)} /><Row label="Assistant found" value={yes(diagnostics.latestAssistantMessageFound)} /><Row label="Citations / sources" value={yes(diagnostics.citationSourceRegionFound)} /><Row label="Thinking block" value={yes(diagnostics.thinkingBlockFound)} /><Row label="Tool / task panel" value={yes(diagnostics.toolTaskPanelFound)} /><Row label="Busy indicators" value={diagnostics.busyIndicators.join(', ') || 'none'} /><Row label="Ready indicators" value={diagnostics.readyIndicators.join(', ') || 'none'} /><Row label="Error indicators" value={diagnostics.errorIndicators.join(', ') || 'none'} /><Row label="Insertion" value={diagnostics.insertionStrategy ?? 'none'} /><Row label="Leader / scheduler" value={(leader ? 'leader' : 'viewer') + ' / ' + (scheduler ?? 'unknown')} /><Row label="Last checked" value={new Date(diagnostics.lastCheckedAt).toLocaleTimeString()} /></dl></section>;
}
