import { useEffect, useState } from 'react';
import { createSafeDiagnosticCopy } from '../../lib/diagnostics'; import { parseSelectorOverridesJson } from '../../lib/selectors'; import { updateSelectorOverrides } from '../../lib/storage';
import type { ProviderDiagnostics, SchedulerState, SelectorOverrides } from '../../lib/types';
function Row({ label, value }: { label: string; value: string }) { return <div className="flex gap-3 py-1"><dt className="w-32 shrink-0 text-zinc-500">{label}</dt><dd className="min-w-0 break-all font-mono">{value}</dd></div>; }
async function activeTabMessage(message: Record<string, unknown>): Promise<unknown> { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab?.id) throw new Error('No active provider tab.'); return chrome.tabs.sendMessage(tab.id, message); }
export function DiagnosticsPanel({ diagnostics, leader, scheduler, overrides = {} }: { diagnostics: ProviderDiagnostics; leader: boolean; scheduler?: SchedulerState; overrides?: SelectorOverrides }) {
  const [copyState, setCopyState] = useState(''); const [overrideText, setOverrideText] = useState(JSON.stringify(overrides, null, 2)); const [overrideState, setOverrideState] = useState('');
  useEffect(() => setOverrideText(JSON.stringify(overrides, null, 2)), [overrides]);
  const yes = (value: boolean) => value ? 'yes' : 'no';
  const copy = async () => { try { await navigator.clipboard.writeText(JSON.stringify(createSafeDiagnosticCopy(diagnostics, leader, scheduler), null, 2)); setCopyState('Diagnostics copied.'); } catch { setCopyState('Copy failed.'); } };
  const highlight = async () => { try { const response = await activeTabMessage({ type: 'HIGHLIGHT_ELEMENTS' }) as { found?: string[] }; setCopyState(response.found?.length ? 'Highlighted: ' + response.found.join(', ') : 'No supported elements were detected.'); } catch { setCopyState('Could not reach the provider tab.'); } };
  const copyEffective = async () => { try { const response = await activeTabMessage({ type: 'GET_EFFECTIVE_SELECTORS' }) as { selectors?: unknown }; if (!response.selectors) throw new Error(); await navigator.clipboard.writeText(JSON.stringify(response.selectors, null, 2)); setOverrideState('Effective selectors copied.'); } catch { setOverrideState('Could not copy effective selectors.'); } };
  const saveOverrides = async () => {
    const result = parseSelectorOverridesJson(overrideText, (selector) => { try { document.querySelector(selector); return true; } catch { return false; } });
    if (!result.ok) { setOverrideState(result.errors.join(' ')); return; }
    await updateSelectorOverrides(diagnostics.providerId, result.value); setOverrideState('Overrides saved. Provider adapter reloaded.');
  };
  const resetOverrides = async () => { await updateSelectorOverrides(diagnostics.providerId, null); setOverrideText('{}'); setOverrideState('Overrides reset to defaults.'); };
  return <section className="card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-sm font-semibold">Debug diagnostics</h2><div className="flex gap-1.5"><button className="btn" onClick={() => void highlight()}>Highlight detected elements</button><button className="btn" onClick={() => void copy()}>Copy diagnostics</button></div></div>{copyState && <p className="mt-2 text-[11px] text-zinc-500" role="status">{copyState}</p>}
    <dl className="mt-3 text-[11px]"><Row label="Provider" value={diagnostics.providerName + ' (' + diagnostics.providerId + ')'} /><Row label="URL" value={diagnostics.url} /><Row label="Conversation" value={diagnostics.conversationId ?? diagnostics.temporaryConversationKey} /><Row label="Experimental" value={yes(diagnostics.experimentalProvider)} /><Row label="Composer" value={yes(diagnostics.composerFound) + ' · ' + diagnostics.composerType} /><Row label="Send / stop" value={yes(diagnostics.sendButtonFound) + ' / ' + yes(diagnostics.stopButtonFound)} /><Row label="Response control" value={yes(diagnostics.regenerateButtonFound)} /><Row label="Assistant found" value={yes(diagnostics.latestAssistantMessageFound)} /><Row label="Citations / sources" value={yes(diagnostics.citationSourceRegionFound)} /><Row label="Thinking block" value={yes(diagnostics.thinkingBlockFound)} /><Row label="Tool / task panel" value={yes(diagnostics.toolTaskPanelFound)} /><Row label="Terminal / output" value={yes(diagnostics.terminalOutputPanelFound)} /><Row label="Overrides" value={diagnostics.selectorOverrideKeys.join(', ') || 'none'} /><Row label="Busy indicators" value={diagnostics.busyIndicators.join(', ') || 'none'} /><Row label="Ready indicators" value={diagnostics.readyIndicators.join(', ') || 'none'} /><Row label="Error indicators" value={diagnostics.errorIndicators.join(', ') || 'none'} /><Row label="Uncertain" value={diagnostics.uncertainReason ?? 'no'} /><Row label="Insertion" value={diagnostics.insertionStrategy ?? 'none'} /><Row label="Leader / scheduler" value={(leader ? 'leader' : 'viewer') + ' / ' + (scheduler ?? 'unknown')} /><Row label="Last checked" value={new Date(diagnostics.lastCheckedAt).toLocaleTimeString()} /></dl>
    {diagnostics.experimentalProvider && <div className="mt-4 border-t border-zinc-200 pt-4 dark:border-zinc-800"><h3 className="text-xs font-semibold">Advanced selector overrides</h3><p className="mt-1 text-[11px] text-amber-600 dark:text-amber-400">Debug-only experimental tuning. JSON CSS selectors run locally and are validated before use.</p><textarea className="field mt-2 min-h-40 font-mono text-[11px]" value={overrideText} onChange={(event) => { setOverrideText(event.target.value); setOverrideState(''); }} spellCheck={false} /><div className="mt-2 flex flex-wrap gap-2"><button className="btn-primary" onClick={() => void saveOverrides()}>Save overrides</button><button className="btn" onClick={() => void resetOverrides()}>Reset provider</button><button className="btn" onClick={() => void copyEffective()}>Copy effective selectors</button></div>{overrideState && <p className="mt-2 text-[11px] text-zinc-500" role="status">{overrideState}</p>}</div>}
  </section>;
}
