import type { ProviderId, ProviderPermissionState } from '../../lib/types';
import { StatusPill } from './StatusPill';
const GROUPS = [{ phase: 1, label: 'Built-in' }, { phase: 2, label: 'Phase 2' }, { phase: 3, label: 'Phase 3' }, { phase: 4, label: 'Future' }] as const;
export function ProvidersPanel({ providers, pending, message, onToggle }: { providers: ProviderPermissionState[]; pending: ProviderId | null; message: string; onToggle: (provider: ProviderPermissionState) => void }) {
  return <section className="card p-4"><div><h2 className="text-sm font-semibold">Providers</h2><p className="mt-1 text-xs text-zinc-500">Optional site access is requested only when you click Enable.</p></div>
    <div className="mt-3 space-y-3">{GROUPS.map((group) => { const entries = providers.filter((provider) => provider.phase === group.phase); return entries.length ? <div key={group.phase}><h3 className="px-1 text-[10px] font-semibold uppercase tracking-wider text-zinc-400">{group.label}</h3><div className="mt-1 divide-y divide-zinc-100 dark:divide-zinc-800">{entries.map((provider) => <div key={provider.id} className="flex items-center gap-2 py-2.5"><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><span className="text-xs font-medium">{provider.name}</span><StatusPill label={provider.builtIn ? 'built-in' : provider.status} tone={provider.builtIn ? 'good' : provider.status === 'planned' ? 'neutral' : 'warn'} /></div><p className="mt-1 text-[11px] text-zinc-500">{provider.status === 'planned' ? 'Planned for Phase 4' : provider.builtIn ? 'Always enabled' : provider.enabled ? 'Enabled · permission granted' : provider.permissionGranted ? 'Disabled · permission retained' : 'Permission required'}</p></div>{!provider.builtIn && provider.status !== 'planned' && <button className={provider.enabled ? 'btn' : 'btn-primary'} disabled={pending === provider.id} onClick={() => onToggle(provider)}>{pending === provider.id ? 'Working…' : provider.enabled ? 'Disable' : 'Enable'}</button>}</div>)}</div></div> : null; })}</div>
    {message && <p className="mt-3 rounded-lg bg-zinc-100 px-3 py-2 text-xs dark:bg-zinc-800" role="status">{message}</p>}
  </section>;
}
